name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update file
      uses: actions/notion-to-file-github-pr@v1.1
      with:
        notion-token: ${{ secrets.NOTION_TOKEN }}
        notion-db: ${{ secrets.NOTION_DATABASE }}
        output-file: './public/database.json'
        output-format: 'json'
        ignore-columns: |
          'Status'
        camelcase-keys: true
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: 'Update from Notion'
        branch: 'automation/update-from-notion'
        delete-branch: true
        title: 'Update from Notion'
        body: 'Automated changes by GitHub action'
        labels: 'automated-notion'
